// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisaCEP.Models;

namespace PesquisaCEP.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200719233445_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PesquisaCEP.Models.End", b =>
                {
                    b.Property<int>("EndId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Cep")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Uf")
                        .HasColumnType("varchar(50)");

                    b.HasKey("EndId");

                    b.ToTable("Ends");
                });
#pragma warning restore 612, 618
        }
    }
}
